 #include <behaviors.dtsi>
#include <dt-bindings/zmk/bt.h>
#include <dt-bindings/zmk/keys.h>
#include <dt-bindings/zmk/pointing.h>
#include <dt-bindings/zmk/mouse.h>

# Bluetoothデバイス名
CONFIG_BT_DEVICE_NAME="KimiBoard-P(BT)"

# USBデバイス名
CONFIG_USB_DEVICE_PRODUCT="KimiBoard-P(USB)"

# トラックボール
CONFIG_ZMK_POINTING=y
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_NFCT_PINS_AS_GPIOS=y

CONFIG_ZMK_MOUSE=y
CONFIG_PMW3610=y
CONFIG_PMW3610_CPI=400
CONFIG_PMW3610_ORIENTATION_180=y
CONFIG_ZMK_BLE=y
CONFIG_BT_MAX_PAIRED=3
CONFIG_PMW3610_POLLING_RATE_125_SW=y
CONFIG_RGBLED_WIDGET=y

CONFIG_PMW3610_SWAP_XY=y
CONFIG_PMW3610_INVERT_X=n
CONFIG_PMW3610_INVERT_Y=y




